cmdlist_dict = {'af_add': {'arg1': 'String',
            'command': 'af_add',
            'comment': 'af_add               String',
            'property': False},
 'af_clr': {'command': 'af_clr',
            'comment': 'af_clr              ',
            'property': False},
 'af_cmdline': {'arg1': 'String',
                'arg2': 'String',
                'command': 'af_cmdline',
                'comment': 'af_cmdline           String Strin',
                'property': False},
 'af_del': {'arg1': 'String',
            'command': 'af_del',
            'comment': 'af_del               String',
            'property': False},
 'af_switch': {'arg1': 'String',
               'command': 'af_switch',
               'comment': 'af_switch            String',
               'property': False},
 'alt_src_step': {'arg1': 'Integer',
                  'command': 'alt_src_step',
                  'comment': 'alt_src_step         Integer',
                  'property': False},
 'ass_use_margins': {'arg1': 'Integer',
                     'command': 'ass_use_margins',
                     'comment': 'ass_use_margins      [Integer]',
                     'property': False},
 'audio_delay': {'arg1': 'Float',
                 'arg2': 'Integer',
                 'command': 'audio_delay',
                 'comment': 'audio_delay          Float [Integer]',
                 'property': False},
 'balance': {'arg1': 'Float',
             'arg2': 'Integer',
             'command': 'balance',
             'comment': 'balance              Float [Integer]',
             'property': False},
 'brightness': {'arg1': 'Integer',
                'arg2': 'Integer',
                'command': 'brightness',
                'comment': 'brightness           Integer [Integer]',
                'property': False},
 'capturing': {'command': 'capturing',
               'comment': 'capturing           ',
               'property': False},
 'change_rectangle': {'arg1': 'Integer',
                      'arg2': 'Integer',
                      'command': 'change_rectangle',
                      'comment': 'change_rectangle     Integer Integer',
                      'property': False},
 'contrast': {'arg1': 'Integer',
              'arg2': 'Integer',
              'command': 'contrast',
              'comment': 'contrast             Integer [Integer]',
              'property': False},
 'dvb_set_channel': {'arg1': 'Integer',
                     'arg2': 'Integer',
                     'command': 'dvb_set_channel',
                     'comment': 'dvb_set_channel      Integer Integer',
                     'property': False},
 'dvdnav': {'arg1': 'String',
            'command': 'dvdnav',
            'comment': 'dvdnav               String',
            'property': False},
 'edl_mark': {'command': 'edl_mark',
              'comment': 'edl_mark            ',
              'property': False},
 'forced_subs_only': {'arg1': 'Integer',
                      'command': 'forced_subs_only',
                      'comment': 'forced_subs_only     [Integer]',
                      'property': False},
 'frame_drop': {'arg1': 'Integer',
                'command': 'frame_drop',
                'comment': 'frame_drop           [Integer]',
                'property': False},
 'frame_step': {'command': 'frame_step',
                'comment': 'frame_step          ',
                'property': False},
 'gamma': {'arg1': 'Integer',
           'arg2': 'Integer',
           'command': 'gamma',
           'comment': 'gamma                Integer [Integer]',
           'property': False},
 'get_audio_bitrate': {'command': 'get_audio_bitrate',
                       'comment': 'get_audio_bitrate   ',
                       'property': False},
 'get_audio_codec': {'command': 'get_audio_codec',
                     'comment': 'get_audio_codec     ',
                     'property': False},
 'get_audio_samples': {'command': 'get_audio_samples',
                       'comment': 'get_audio_samples   ',
                       'property': False},
 'get_file_name': {'command': 'get_file_name',
                   'comment': 'get_file_name       ',
                   'property': False},
 'get_meta_album': {'command': 'get_meta_album',
                    'comment': 'get_meta_album      ',
                    'property': False},
 'get_meta_artist': {'command': 'get_meta_artist',
                     'comment': 'get_meta_artist     ',
                     'property': False},
 'get_meta_comment': {'command': 'get_meta_comment',
                      'comment': 'get_meta_comment    ',
                      'property': False},
 'get_meta_genre': {'command': 'get_meta_genre',
                    'comment': 'get_meta_genre      ',
                    'property': False},
 'get_meta_title': {'command': 'get_meta_title',
                    'comment': 'get_meta_title      ',
                    'property': False},
 'get_meta_track': {'command': 'get_meta_track',
                    'comment': 'get_meta_track      ',
                    'property': False},
 'get_meta_year': {'command': 'get_meta_year',
                   'comment': 'get_meta_year       ',
                   'property': False},
 'get_percent_pos': {'command': 'get_percent_pos',
                     'comment': 'get_percent_pos     ',
                     'property': False},
 'get_property': {'arg1': 'String',
                  'command': 'get_property',
                  'comment': 'get_property         String',
                  'property': False},
 'get_sub_visibility': {'command': 'get_sub_visibility',
                        'comment': 'get_sub_visibility  ',
                        'property': False},
 'get_time_length': {'command': 'get_time_length',
                     'comment': 'get_time_length     ',
                     'property': False},
 'get_time_pos': {'command': 'get_time_pos',
                  'comment': 'get_time_pos        ',
                  'property': False},
 'get_video_bitrate': {'command': 'get_video_bitrate',
                       'comment': 'get_video_bitrate   ',
                       'property': False},
 'get_video_codec': {'command': 'get_video_codec',
                     'comment': 'get_video_codec     ',
                     'property': False},
 'get_video_resolution': {'command': 'get_video_resolution',
                          'comment': 'get_video_resolution',
                          'property': False},
 'get_vo_fullscreen': {'command': 'get_vo_fullscreen',
                       'comment': 'get_vo_fullscreen   ',
                       'property': False},
 'hue': {'arg1': 'Integer',
         'arg2': 'Integer',
         'command': 'hue',
         'comment': 'hue                  Integer [Integer]',
         'property': False},
 'key_down_event': {'arg1': 'Integer',
                    'command': 'key_down_event',
                    'comment': 'key_down_event       Integer',
                    'property': False},
 'loadfile': {'arg1': 'String',
              'arg2': 'Integer',
              'command': 'loadfile',
              'comment': 'loadfile             String [Integer]',
              'property': False},
 'loadlist': {'arg1': 'String',
              'arg2': 'Integer',
              'command': 'loadlist',
              'comment': 'loadlist             String [Integer]',
              'property': False},
 'loop': {'arg1': 'Integer',
          'arg2': 'Integer',
          'command': 'loop',
          'comment': 'loop                 Integer [Integer]',
          'property': False},
 'mute': {'arg1': 'Integer',
          'command': 'mute',
          'comment': 'mute                 [Integer]',
          'property': False},
 'osd': {'arg1': 'Integer',
         'command': 'osd',
         'comment': 'osd                  [Integer]',
         'property': False},
 'osd_show_progression': {'command': 'osd_show_progression',
                          'comment': 'osd_show_progression',
                          'property': False},
 'osd_show_property_te': {'arg1': 'String',
                          'arg2': 'Integer',
                          'arg3': 'Integer',
                          'command': 'osd_show_property_te',
                          'comment': 'osd_show_property_te String [Integer] [Integer]',
                          'property': False},
 'osd_show_text': {'arg1': 'String',
                   'arg2': 'Integer',
                   'arg3': 'Integer',
                   'command': 'osd_show_text',
                   'comment': 'osd_show_text        String [Integer] [Integer]',
                   'property': False},
 'panscan': {'arg1': 'Float',
             'arg2': 'Integer',
             'command': 'panscan',
             'comment': 'panscan              Float [Integer]',
             'property': False},
 'pause': {'command': 'pause',
           'comment': 'pause               ',
           'property': False},
 'pt_step': {'arg1': 'Integer',
             'arg2': 'Integer',
             'command': 'pt_step',
             'comment': 'pt_step              Integer [Integer]',
             'property': False},
 'pt_up_step': {'arg1': 'Integer',
                'arg2': 'Integer',
                'command': 'pt_up_step',
                'comment': 'pt_up_step           Integer [Integer]',
                'property': False},
 'quit': {'arg1': 'Integer',
          'command': 'quit',
          'comment': 'quit                 [Integer]',
          'property': False},
 'run': {'arg1': 'String',
         'command': 'run',
         'comment': 'run                  String',
         'property': False},
 'saturation': {'arg1': 'Integer',
                'arg2': 'Integer',
                'command': 'saturation',
                'comment': 'saturation           Integer [Integer]',
                'property': False},
 'screenshot': {'arg1': 'Integer',
                'arg2': 'Integer',
                'command': 'screenshot',
                'comment': 'screenshot           [Integer] [Integer]',
                'property': False},
 'seek': {'arg1': 'Float',
          'arg2': 'Integer',
          'arg3': 'Integer',
          'command': 'seek',
          'comment': 'seek                 Float [Integer] [Integer]',
          'property': False},
 'seek_chapter': {'arg1': 'Integer',
                  'arg2': 'Integer',
                  'command': 'seek_chapter',
                  'comment': 'seek_chapter         Integer [Integer]',
                  'property': False},
 'set_mouse_pos': {'arg1': 'Integer',
                   'arg2': 'Integer',
                   'command': 'set_mouse_pos',
                   'comment': 'set_mouse_pos        Integer Integer',
                   'property': False},
 'set_property': {'arg1': 'String',
                  'arg2': 'String',
                  'command': 'set_property',
                  'comment': 'set_property         String String',
                  'property': False},
 'set_property_osd': {'arg1': 'String',
                      'arg2': 'String',
                      'command': 'set_property_osd',
                      'comment': 'set_property_osd     String String',
                      'property': False},
 'speed_incr': {'arg1': 'Float',
                'command': 'speed_incr',
                'comment': 'speed_incr           Float',
                'property': False},
 'speed_mult': {'arg1': 'Float',
                'command': 'speed_mult',
                'comment': 'speed_mult           Float',
                'property': False},
 'speed_set': {'arg1': 'Float',
               'command': 'speed_set',
               'comment': 'speed_set            Float',
               'property': False},
 'step_property': {'arg1': 'String',
                   'arg2': 'Float',
                   'arg3': 'Integer',
                   'command': 'step_property',
                   'comment': 'step_property        String [Float] [Integer]',
                   'property': False},
 'step_property_osd': {'arg1': 'String',
                       'arg2': 'Float',
                       'arg3': 'Integer',
                       'command': 'step_property_osd',
                       'comment': 'step_property_osd    String [Float] [Integer]',
                       'property': False},
 'stop': {'command': 'stop',
          'comment': 'stop                ',
          'property': False},
 'sub_alignment': {'arg1': 'Integer',
                   'command': 'sub_alignment',
                   'comment': 'sub_alignment        [Integer]',
                   'property': False},
 'sub_delay': {'arg1': 'Float',
               'arg2': 'Integer',
               'command': 'sub_delay',
               'comment': 'sub_delay            Float [Integer]',
               'property': False},
 'sub_demux': {'arg1': 'Integer',
               'command': 'sub_demux',
               'comment': 'sub_demux            [Integer]',
               'property': False},
 'sub_file': {'arg1': 'Integer',
              'command': 'sub_file',
              'comment': 'sub_file             [Integer]',
              'property': False},
 'sub_load': {'arg1': 'String',
              'command': 'sub_load',
              'comment': 'sub_load             String',
              'property': False},
 'sub_log': {'command': 'sub_log',
             'comment': 'sub_log             ',
             'property': False},
 'sub_pos': {'arg1': 'Integer',
             'arg2': 'Integer',
             'command': 'sub_pos',
             'comment': 'sub_pos              Integer [Integer]',
             'property': False},
 'sub_remove': {'arg1': 'Integer',
                'command': 'sub_remove',
                'comment': 'sub_remove           [Integer]',
                'property': False},
 'sub_scale': {'arg1': 'Float',
               'arg2': 'Integer',
               'command': 'sub_scale',
               'comment': 'sub_scale            Float [Integer]',
               'property': False},
 'sub_select': {'arg1': 'Integer',
                'command': 'sub_select',
                'comment': 'sub_select           [Integer]',
                'property': False},
 'sub_source': {'arg1': 'Integer',
                'command': 'sub_source',
                'comment': 'sub_source           [Integer]',
                'property': False},
 'sub_step': {'arg1': 'Integer',
              'arg2': 'Integer',
              'command': 'sub_step',
              'comment': 'sub_step             Integer [Integer]',
              'property': False},
 'sub_visibility': {'arg1': 'Integer',
                    'command': 'sub_visibility',
                    'comment': 'sub_visibility       [Integer]',
                    'property': False},
 'sub_vob': {'arg1': 'Integer',
             'command': 'sub_vob',
             'comment': 'sub_vob              [Integer]',
             'property': False},
 'switch_angle': {'arg1': 'Integer',
                  'command': 'switch_angle',
                  'comment': 'switch_angle         [Integer]',
                  'property': False},
 'switch_audio': {'arg1': 'Integer',
                  'command': 'switch_audio',
                  'comment': 'switch_audio         [Integer]',
                  'property': False},
 'switch_ratio': {'arg1': 'Float',
                  'command': 'switch_ratio',
                  'comment': 'switch_ratio         [Float]',
                  'property': False},
 'switch_title': {'arg1': 'Integer',
                  'command': 'switch_title',
                  'comment': 'switch_title         [Integer]',
                  'property': False},
 'switch_vsync': {'arg1': 'Integer',
                  'command': 'switch_vsync',
                  'comment': 'switch_vsync         [Integer]',
                  'property': False},
 'teletext_add_dec': {'arg1': 'String',
                      'command': 'teletext_add_dec',
                      'comment': 'teletext_add_dec     String',
                      'property': False},
 'teletext_go_link': {'arg1': 'Integer',
                      'command': 'teletext_go_link',
                      'comment': 'teletext_go_link     Integer',
                      'property': False},
 'tv_last_channel': {'command': 'tv_last_channel',
                     'comment': 'tv_last_channel     ',
                     'property': False},
 'tv_set_brightness': {'arg1': 'Integer',
                       'arg2': 'Integer',
                       'command': 'tv_set_brightness',
                       'comment': 'tv_set_brightness    Integer [Integer]',
                       'property': False},
 'tv_set_channel': {'arg1': 'String',
                    'command': 'tv_set_channel',
                    'comment': 'tv_set_channel       String',
                    'property': False},
 'tv_set_contrast': {'arg1': 'Integer',
                     'arg2': 'Integer',
                     'command': 'tv_set_contrast',
                     'comment': 'tv_set_contrast      Integer [Integer]',
                     'property': False},
 'tv_set_freq': {'arg1': 'Float',
                 'command': 'tv_set_freq',
                 'comment': 'tv_set_freq          Float',
                 'property': False},
 'tv_set_hue': {'arg1': 'Integer',
                'arg2': 'Integer',
                'command': 'tv_set_hue',
                'comment': 'tv_set_hue           Integer [Integer]',
                'property': False},
 'tv_set_norm': {'arg1': 'String',
                 'command': 'tv_set_norm',
                 'comment': 'tv_set_norm          String',
                 'property': False},
 'tv_set_saturation': {'arg1': 'Integer',
                       'arg2': 'Integer',
                       'command': 'tv_set_saturation',
                       'comment': 'tv_set_saturation    Integer [Integer]',
                       'property': False},
 'tv_start_scan': {'command': 'tv_start_scan',
                   'comment': 'tv_start_scan       ',
                   'property': False},
 'tv_step_chanlist': {'command': 'tv_step_chanlist',
                      'comment': 'tv_step_chanlist    ',
                      'property': False},
 'tv_step_channel': {'arg1': 'Integer',
                     'command': 'tv_step_channel',
                     'comment': 'tv_step_channel      Integer',
                     'property': False},
 'tv_step_freq': {'arg1': 'Float',
                  'command': 'tv_step_freq',
                  'comment': 'tv_step_freq         Float',
                  'property': False},
 'tv_step_norm': {'command': 'tv_step_norm',
                  'comment': 'tv_step_norm        ',
                  'property': False},
 'use_master': {'command': 'use_master',
                'comment': 'use_master          ',
                'property': False},
 'vo_border': {'arg1': 'Integer',
               'command': 'vo_border',
               'comment': 'vo_border            [Integer]',
               'property': False},
 'vo_fullscreen': {'arg1': 'Integer',
                   'command': 'vo_fullscreen',
                   'comment': 'vo_fullscreen        [Integer]',
                   'property': False},
 'vo_ontop': {'arg1': 'Integer',
              'command': 'vo_ontop',
              'comment': 'vo_ontop             [Integer]',
              'property': False},
 'vo_rootwin': {'arg1': 'Integer',
                'command': 'vo_rootwin',
                'comment': 'vo_rootwin           [Integer]',
                'property': False},
 'vobsub_lang': {'arg1': 'Integer',
                 'command': 'vobsub_lang',
                 'comment': 'vobsub_lang          [Integer]',
                 'property': False},
 'volume': {'arg1': 'Float',
            'arg2': 'Integer',
            'command': 'volume',
            'comment': 'volume               Float [Integer]',
            'property': False}}