cmdlist_dict = {'af_add': {'command': 'af_add',
            'comment': 'af_add               String',
            'property': False,
            'types': ['str']},
 'af_clr': {'command': 'af_clr',
            'comment': 'af_clr              ',
            'property': False,
            'types': []},
 'af_cmdline': {'command': 'af_cmdline',
                'comment': 'af_cmdline           String Strin',
                'property': False,
                'types': ['str', 'str']},
 'af_del': {'command': 'af_del',
            'comment': 'af_del               String',
            'property': False,
            'types': ['str']},
 'af_switch': {'command': 'af_switch',
               'comment': 'af_switch            String',
               'property': False,
               'types': ['str']},
 'alt_src_step': {'command': 'alt_src_step',
                  'comment': 'alt_src_step         Integer',
                  'property': False,
                  'types': ['int']},
 'ass_use_margins': {'command': 'ass_use_margins',
                     'comment': 'ass_use_margins      [Integer]',
                     'property': False,
                     'types': ['int']},
 'audio_delay': {'command': 'audio_delay',
                 'comment': 'audio_delay          Float [Integer]',
                 'property': False,
                 'types': ['float', 'int']},
 'balance': {'command': 'balance',
             'comment': 'balance              Float [Integer]',
             'property': False,
             'types': ['float', 'int']},
 'brightness': {'command': 'brightness',
                'comment': 'brightness           Integer [Integer]',
                'property': False,
                'types': ['int', 'int']},
 'capturing': {'command': 'capturing',
               'comment': 'capturing           ',
               'property': False,
               'types': []},
 'change_rectangle': {'command': 'change_rectangle',
                      'comment': 'change_rectangle     Integer Integer',
                      'property': False,
                      'types': ['int', 'int']},
 'contrast': {'command': 'contrast',
              'comment': 'contrast             Integer [Integer]',
              'property': False,
              'types': ['int', 'int']},
 'dvb_set_channel': {'command': 'dvb_set_channel',
                     'comment': 'dvb_set_channel      Integer Integer',
                     'property': False,
                     'types': ['int', 'int']},
 'dvdnav': {'command': 'dvdnav',
            'comment': 'dvdnav               String',
            'property': False,
            'types': ['str']},
 'edl_mark': {'command': 'edl_mark',
              'comment': 'edl_mark            ',
              'property': False,
              'types': []},
 'forced_subs_only': {'command': 'forced_subs_only',
                      'comment': 'forced_subs_only     [Integer]',
                      'property': False,
                      'types': ['int']},
 'frame_drop': {'command': 'frame_drop',
                'comment': 'frame_drop           [Integer]',
                'property': False,
                'types': ['int']},
 'frame_step': {'command': 'frame_step',
                'comment': 'frame_step          ',
                'property': False,
                'types': []},
 'gamma': {'command': 'gamma',
           'comment': 'gamma                Integer [Integer]',
           'property': False,
           'types': ['int', 'int']},
 'get_audio_bitrate': {'command': 'get_audio_bitrate',
                       'comment': 'get_audio_bitrate   ',
                       'property': False,
                       'types': []},
 'get_audio_codec': {'command': 'get_audio_codec',
                     'comment': 'get_audio_codec     ',
                     'property': False,
                     'types': []},
 'get_audio_samples': {'command': 'get_audio_samples',
                       'comment': 'get_audio_samples   ',
                       'property': False,
                       'types': []},
 'get_file_name': {'command': 'get_file_name',
                   'comment': 'get_file_name       ',
                   'property': False,
                   'types': []},
 'get_meta_album': {'command': 'get_meta_album',
                    'comment': 'get_meta_album      ',
                    'property': False,
                    'types': []},
 'get_meta_artist': {'command': 'get_meta_artist',
                     'comment': 'get_meta_artist     ',
                     'property': False,
                     'types': []},
 'get_meta_comment': {'command': 'get_meta_comment',
                      'comment': 'get_meta_comment    ',
                      'property': False,
                      'types': []},
 'get_meta_genre': {'command': 'get_meta_genre',
                    'comment': 'get_meta_genre      ',
                    'property': False,
                    'types': []},
 'get_meta_title': {'command': 'get_meta_title',
                    'comment': 'get_meta_title      ',
                    'property': False,
                    'types': []},
 'get_meta_track': {'command': 'get_meta_track',
                    'comment': 'get_meta_track      ',
                    'property': False,
                    'types': []},
 'get_meta_year': {'command': 'get_meta_year',
                   'comment': 'get_meta_year       ',
                   'property': False,
                   'types': []},
 'get_percent_pos': {'command': 'get_percent_pos',
                     'comment': 'get_percent_pos     ',
                     'property': False,
                     'types': []},
 'get_property': {'command': 'get_property',
                  'comment': 'get_property         String',
                  'property': False,
                  'types': ['str']},
 'get_sub_visibility': {'command': 'get_sub_visibility',
                        'comment': 'get_sub_visibility  ',
                        'property': False,
                        'types': []},
 'get_time_length': {'command': 'get_time_length',
                     'comment': 'get_time_length     ',
                     'property': False,
                     'types': []},
 'get_time_pos': {'command': 'get_time_pos',
                  'comment': 'get_time_pos        ',
                  'property': False,
                  'types': []},
 'get_video_bitrate': {'command': 'get_video_bitrate',
                       'comment': 'get_video_bitrate   ',
                       'property': False,
                       'types': []},
 'get_video_codec': {'command': 'get_video_codec',
                     'comment': 'get_video_codec     ',
                     'property': False,
                     'types': []},
 'get_video_resolution': {'command': 'get_video_resolution',
                          'comment': 'get_video_resolution',
                          'property': False,
                          'types': []},
 'get_vo_fullscreen': {'command': 'get_vo_fullscreen',
                       'comment': 'get_vo_fullscreen   ',
                       'property': False,
                       'types': []},
 'hue': {'command': 'hue',
         'comment': 'hue                  Integer [Integer]',
         'property': False,
         'types': ['int', 'int']},
 'key_down_event': {'command': 'key_down_event',
                    'comment': 'key_down_event       Integer',
                    'property': False,
                    'types': ['int']},
 'loadfile': {'command': 'loadfile',
              'comment': 'loadfile             String [Integer]',
              'property': False,
              'types': ['str', 'int']},
 'loadlist': {'command': 'loadlist',
              'comment': 'loadlist             String [Integer]',
              'property': False,
              'types': ['str', 'int']},
 'loop': {'command': 'loop',
          'comment': 'loop                 Integer [Integer]',
          'property': False,
          'types': ['int', 'int']},
 'mute': {'command': 'mute',
          'comment': 'mute                 [Integer]',
          'property': False,
          'types': ['int']},
 'osd': {'command': 'osd',
         'comment': 'osd                  [Integer]',
         'property': False,
         'types': ['int']},
 'osd_show_progression': {'command': 'osd_show_progression',
                          'comment': 'osd_show_progression',
                          'property': False,
                          'types': []},
 'osd_show_property_te': {'command': 'osd_show_property_te',
                          'comment': 'osd_show_property_te String [Integer] [Integer]',
                          'property': False,
                          'types': ['str', 'int', 'int']},
 'osd_show_text': {'command': 'osd_show_text',
                   'comment': 'osd_show_text        String [Integer] [Integer]',
                   'property': False,
                   'types': ['str', 'int', 'int']},
 'panscan': {'command': 'panscan',
             'comment': 'panscan              Float [Integer]',
             'property': False,
             'types': ['float', 'int']},
 'pause': {'command': 'pause',
           'comment': 'pause               ',
           'property': False,
           'types': []},
 'pt_step': {'command': 'pt_step',
             'comment': 'pt_step              Integer [Integer]',
             'property': False,
             'types': ['int', 'int']},
 'pt_up_step': {'command': 'pt_up_step',
                'comment': 'pt_up_step           Integer [Integer]',
                'property': False,
                'types': ['int', 'int']},
 'quit': {'command': 'quit',
          'comment': 'quit                 [Integer]',
          'property': False,
          'types': ['int']},
 'run': {'command': 'run',
         'comment': 'run                  String',
         'property': False,
         'types': ['str']},
 'saturation': {'command': 'saturation',
                'comment': 'saturation           Integer [Integer]',
                'property': False,
                'types': ['int', 'int']},
 'screenshot': {'command': 'screenshot',
                'comment': 'screenshot           [Integer] [Integer]',
                'property': False,
                'types': ['int', 'int']},
 'seek': {'command': 'seek',
          'comment': 'seek                 Float [Integer] [Integer]',
          'property': False,
          'types': ['float', 'int', 'int']},
 'seek_chapter': {'command': 'seek_chapter',
                  'comment': 'seek_chapter         Integer [Integer]',
                  'property': False,
                  'types': ['int', 'int']},
 'set_mouse_pos': {'command': 'set_mouse_pos',
                   'comment': 'set_mouse_pos        Integer Integer',
                   'property': False,
                   'types': ['int', 'int']},
 'set_property': {'command': 'set_property',
                  'comment': 'set_property         String String',
                  'property': False,
                  'types': ['str', 'str']},
 'set_property_osd': {'command': 'set_property_osd',
                      'comment': 'set_property_osd     String String',
                      'property': False,
                      'types': ['str', 'str']},
 'speed_incr': {'command': 'speed_incr',
                'comment': 'speed_incr           Float',
                'property': False,
                'types': ['float']},
 'speed_mult': {'command': 'speed_mult',
                'comment': 'speed_mult           Float',
                'property': False,
                'types': ['float']},
 'speed_set': {'command': 'speed_set',
               'comment': 'speed_set            Float',
               'property': False,
               'types': ['float']},
 'step_property': {'command': 'step_property',
                   'comment': 'step_property        String [Float] [Integer]',
                   'property': False,
                   'types': ['str', 'float', 'int']},
 'step_property_osd': {'command': 'step_property_osd',
                       'comment': 'step_property_osd    String [Float] [Integer]',
                       'property': False,
                       'types': ['str', 'float', 'int']},
 'stop': {'command': 'stop',
          'comment': 'stop                ',
          'property': False,
          'types': []},
 'sub_alignment': {'command': 'sub_alignment',
                   'comment': 'sub_alignment        [Integer]',
                   'property': False,
                   'types': ['int']},
 'sub_delay': {'command': 'sub_delay',
               'comment': 'sub_delay            Float [Integer]',
               'property': False,
               'types': ['float', 'int']},
 'sub_demux': {'command': 'sub_demux',
               'comment': 'sub_demux            [Integer]',
               'property': False,
               'types': ['int']},
 'sub_file': {'command': 'sub_file',
              'comment': 'sub_file             [Integer]',
              'property': False,
              'types': ['int']},
 'sub_load': {'command': 'sub_load',
              'comment': 'sub_load             String',
              'property': False,
              'types': ['str']},
 'sub_log': {'command': 'sub_log',
             'comment': 'sub_log             ',
             'property': False,
             'types': []},
 'sub_pos': {'command': 'sub_pos',
             'comment': 'sub_pos              Integer [Integer]',
             'property': False,
             'types': ['int', 'int']},
 'sub_remove': {'command': 'sub_remove',
                'comment': 'sub_remove           [Integer]',
                'property': False,
                'types': ['int']},
 'sub_scale': {'command': 'sub_scale',
               'comment': 'sub_scale            Float [Integer]',
               'property': False,
               'types': ['float', 'int']},
 'sub_select': {'command': 'sub_select',
                'comment': 'sub_select           [Integer]',
                'property': False,
                'types': ['int']},
 'sub_source': {'command': 'sub_source',
                'comment': 'sub_source           [Integer]',
                'property': False,
                'types': ['int']},
 'sub_step': {'command': 'sub_step',
              'comment': 'sub_step             Integer [Integer]',
              'property': False,
              'types': ['int', 'int']},
 'sub_visibility': {'command': 'sub_visibility',
                    'comment': 'sub_visibility       [Integer]',
                    'property': False,
                    'types': ['int']},
 'sub_vob': {'command': 'sub_vob',
             'comment': 'sub_vob              [Integer]',
             'property': False,
             'types': ['int']},
 'switch_angle': {'command': 'switch_angle',
                  'comment': 'switch_angle         [Integer]',
                  'property': False,
                  'types': ['int']},
 'switch_audio': {'command': 'switch_audio',
                  'comment': 'switch_audio         [Integer]',
                  'property': False,
                  'types': ['int']},
 'switch_ratio': {'command': 'switch_ratio',
                  'comment': 'switch_ratio         [Float]',
                  'property': False,
                  'types': ['float']},
 'switch_title': {'command': 'switch_title',
                  'comment': 'switch_title         [Integer]',
                  'property': False,
                  'types': ['int']},
 'switch_vsync': {'command': 'switch_vsync',
                  'comment': 'switch_vsync         [Integer]',
                  'property': False,
                  'types': ['int']},
 'teletext_add_dec': {'command': 'teletext_add_dec',
                      'comment': 'teletext_add_dec     String',
                      'property': False,
                      'types': ['str']},
 'teletext_go_link': {'command': 'teletext_go_link',
                      'comment': 'teletext_go_link     Integer',
                      'property': False,
                      'types': ['int']},
 'tv_last_channel': {'command': 'tv_last_channel',
                     'comment': 'tv_last_channel     ',
                     'property': False,
                     'types': []},
 'tv_set_brightness': {'command': 'tv_set_brightness',
                       'comment': 'tv_set_brightness    Integer [Integer]',
                       'property': False,
                       'types': ['int', 'int']},
 'tv_set_channel': {'command': 'tv_set_channel',
                    'comment': 'tv_set_channel       String',
                    'property': False,
                    'types': ['str']},
 'tv_set_contrast': {'command': 'tv_set_contrast',
                     'comment': 'tv_set_contrast      Integer [Integer]',
                     'property': False,
                     'types': ['int', 'int']},
 'tv_set_freq': {'command': 'tv_set_freq',
                 'comment': 'tv_set_freq          Float',
                 'property': False,
                 'types': ['float']},
 'tv_set_hue': {'command': 'tv_set_hue',
                'comment': 'tv_set_hue           Integer [Integer]',
                'property': False,
                'types': ['int', 'int']},
 'tv_set_norm': {'command': 'tv_set_norm',
                 'comment': 'tv_set_norm          String',
                 'property': False,
                 'types': ['str']},
 'tv_set_saturation': {'command': 'tv_set_saturation',
                       'comment': 'tv_set_saturation    Integer [Integer]',
                       'property': False,
                       'types': ['int', 'int']},
 'tv_start_scan': {'command': 'tv_start_scan',
                   'comment': 'tv_start_scan       ',
                   'property': False,
                   'types': []},
 'tv_step_chanlist': {'command': 'tv_step_chanlist',
                      'comment': 'tv_step_chanlist    ',
                      'property': False,
                      'types': []},
 'tv_step_channel': {'command': 'tv_step_channel',
                     'comment': 'tv_step_channel      Integer',
                     'property': False,
                     'types': ['int']},
 'tv_step_freq': {'command': 'tv_step_freq',
                  'comment': 'tv_step_freq         Float',
                  'property': False,
                  'types': ['float']},
 'tv_step_norm': {'command': 'tv_step_norm',
                  'comment': 'tv_step_norm        ',
                  'property': False,
                  'types': []},
 'use_master': {'command': 'use_master',
                'comment': 'use_master          ',
                'property': False,
                'types': []},
 'vo_border': {'command': 'vo_border',
               'comment': 'vo_border            [Integer]',
               'property': False,
               'types': ['int']},
 'vo_fullscreen': {'command': 'vo_fullscreen',
                   'comment': 'vo_fullscreen        [Integer]',
                   'property': False,
                   'types': ['int']},
 'vo_ontop': {'command': 'vo_ontop',
              'comment': 'vo_ontop             [Integer]',
              'property': False,
              'types': ['int']},
 'vo_rootwin': {'command': 'vo_rootwin',
                'comment': 'vo_rootwin           [Integer]',
                'property': False,
                'types': ['int']},
 'vobsub_lang': {'command': 'vobsub_lang',
                 'comment': 'vobsub_lang          [Integer]',
                 'property': False,
                 'types': ['int']},
 'volume': {'command': 'volume',
            'comment': 'volume               Float [Integer]',
            'property': False,
            'types': ['float', 'int']}}