property_dict = {'angle': {'command': 'angle',
           'comment': 'select angle',
           'get': True,
           'max': False,
           'min': 0,
           'set': True,
           'step': True,
           'type': 'int'},
 'aspect': {'command': 'aspect',
            'comment': '',
            'get': True,
            'max': False,
            'min': False,
            'set': False,
            'step': False,
            'type': 'float'},
 'audio_bitrate': {'command': 'audio_bitrate',
                   'comment': '',
                   'get': True,
                   'max': False,
                   'min': False,
                   'set': False,
                   'step': False,
                   'type': 'int'},
 'audio_codec': {'command': 'audio_codec',
                 'comment': '',
                 'get': True,
                 'max': False,
                 'min': False,
                 'set': False,
                 'step': False,
                 'type': 'str'},
 'audio_delay': {'command': 'audio_delay',
                 'comment': '',
                 'get': True,
                 'max': 100,
                 'min': -100,
                 'set': True,
                 'step': True,
                 'type': 'float'},
 'audio_format': {'command': 'audio_format',
                  'comment': '',
                  'get': True,
                  'max': False,
                  'min': False,
                  'set': False,
                  'step': False,
                  'type': 'int'},
 'balance': {'command': 'balance',
             'comment': 'change audio balance',
             'get': True,
             'max': 1,
             'min': -1,
             'set': True,
             'step': True,
             'type': 'float'},
 'border': {'command': 'border',
            'comment': '',
            'get': True,
            'max': 1,
            'min': 0,
            'set': True,
            'step': True,
            'type': 'flag'},
 'brightness': {'command': 'brightness',
                'comment': '',
                'get': True,
                'max': 100,
                'min': -100,
                'set': True,
                'step': True,
                'type': 'int'},
 'capturing': {'command': 'capturing',
               'comment': 'dump primary stream if enabled',
               'get': True,
               'max': 1,
               'min': 0,
               'set': True,
               'step': True,
               'type': 'flag'},
 'channels': {'command': 'channels',
              'comment': '',
              'get': True,
              'max': False,
              'min': False,
              'set': False,
              'step': False,
              'type': 'int'},
 'chapter': {'command': 'chapter',
             'comment': 'select chapter',
             'get': True,
             'max': False,
             'min': 0,
             'set': True,
             'step': True,
             'type': 'int'},
 'chapters': {'command': 'chapters',
              'comment': 'number of chapters',
              'get': True,
              'max': False,
              'min': False,
              'set': False,
              'step': False,
              'type': 'int'},
 'contrast': {'command': 'contrast',
              'comment': '',
              'get': True,
              'max': 100,
              'min': -100,
              'set': True,
              'step': True,
              'type': 'int'},
 'deinterlace': {'command': 'deinterlace',
                 'comment': '',
                 'get': True,
                 'max': 1,
                 'min': 0,
                 'set': True,
                 'step': True,
                 'type': 'flag'},
 'demuxer': {'command': 'demuxer',
             'comment': 'demuxer used',
             'get': True,
             'max': False,
             'min': False,
             'set': False,
             'step': False,
             'type': 'str'},
 'filename': {'command': 'filename',
              'comment': 'file playing wo path',
              'get': True,
              'max': False,
              'min': False,
              'set': False,
              'step': False,
              'type': 'str'},
 'fps': {'command': 'fps',
         'comment': '',
         'get': True,
         'max': False,
         'min': False,
         'set': False,
         'step': False,
         'type': 'float'},
 'framedropping': {'command': 'framedropping',
                   'comment': '1 = soft, 2 = hard',
                   'get': True,
                   'max': 2,
                   'min': 0,
                   'set': True,
                   'step': True,
                   'type': 'int'},
 'fullscreen': {'command': 'fullscreen',
                'comment': '',
                'get': True,
                'max': 1,
                'min': 0,
                'set': True,
                'step': True,
                'type': 'flag'},
 'gamma': {'command': 'gamma',
           'comment': '',
           'get': True,
           'max': 100,
           'min': -100,
           'set': True,
           'step': True,
           'type': 'int'},
 'height': {'command': 'height',
            'comment': '"display" height',
            'get': True,
            'max': False,
            'min': False,
            'set': False,
            'step': False,
            'type': 'int'},
 'hue': {'command': 'hue',
         'comment': '',
         'get': True,
         'max': 100,
         'min': -100,
         'set': True,
         'step': True,
         'type': 'int'},
 'length': {'command': 'length',
            'comment': 'length of file in seconds',
            'get': True,
            'max': False,
            'min': False,
            'set': False,
            'step': False,
            'type': 'float'},
 'loop': {'command': 'loop',
          'comment': 'as -loop',
          'get': True,
          'max': False,
          'min': -1,
          'set': True,
          'step': True,
          'type': 'int'},
 'metadata': {'command': 'metadata',
              'comment': 'list of metadata key/value',
              'get': True,
              'max': False,
              'min': False,
              'set': False,
              'step': False,
              'type': 'str'},
 'metadata/*': {'command': 'metadata/*',
                'comment': 'metadata values',
                'get': True,
                'max': False,
                'min': False,
                'set': False,
                'step': False,
                'type': 'str'},
 'mute': {'command': 'mute',
          'comment': '',
          'get': True,
          'max': 1,
          'min': 0,
          'set': True,
          'step': True,
          'type': 'flag'},
 'ontop': {'command': 'ontop',
           'comment': '',
           'get': True,
           'max': 1,
           'min': 0,
           'set': True,
           'step': True,
           'type': 'flag'},
 'osdlevel': {'command': 'osdlevel',
              'comment': 'as -osdlevel',
              'get': True,
              'max': 3,
              'min': 0,
              'set': True,
              'step': True,
              'type': 'int'},
 'panscan': {'command': 'panscan',
             'comment': '',
             'get': True,
             'max': 1,
             'min': 0,
             'set': True,
             'step': True,
             'type': 'float'},
 'path': {'command': 'path',
          'comment': 'file playing',
          'get': True,
          'max': False,
          'min': False,
          'set': False,
          'step': False,
          'type': 'str'},
 'pause': {'command': 'pause',
           'comment': '1 if paused, use with pausing_keep_force',
           'get': True,
           'max': 1,
           'min': 0,
           'set': False,
           'step': False,
           'type': 'flag'},
 'percent_pos': {'command': 'percent_pos',
                 'comment': 'position in percent',
                 'get': True,
                 'max': 100,
                 'min': 0,
                 'set': True,
                 'step': True,
                 'type': 'int'},
 'rootwin': {'command': 'rootwin',
             'comment': '',
             'get': True,
             'max': 1,
             'min': 0,
             'set': True,
             'step': True,
             'type': 'flag'},
 'samplerate': {'command': 'samplerate',
                'comment': '',
                'get': True,
                'max': False,
                'min': False,
                'set': False,
                'step': False,
                'type': 'int'},
 'saturation': {'command': 'saturation',
                'comment': '',
                'get': True,
                'max': 100,
                'min': -100,
                'set': True,
                'step': True,
                'type': 'int'},
 'speed': {'command': 'speed',
           'comment': 'as -speed',
           'get': True,
           'max': 100,
           'min': 0.01,
           'set': True,
           'step': True,
           'type': 'float'},
 'stream_end': {'command': 'stream_end',
                'comment': 'end pos in stream',
                'get': True,
                'max': False,
                'min': 0,
                'set': False,
                'step': False,
                'type': 'int'},
 'stream_length': {'command': 'stream_length',
                   'comment': '(end - start)',
                   'get': True,
                   'max': False,
                   'min': 0,
                   'set': False,
                   'step': False,
                   'type': 'int'},
 'stream_pos': {'command': 'stream_pos',
                'comment': 'position in stream',
                'get': True,
                'max': False,
                'min': 0,
                'set': True,
                'step': False,
                'type': 'int'},
 'stream_start': {'command': 'stream_start',
                  'comment': 'start pos in stream',
                  'get': True,
                  'max': False,
                  'min': 0,
                  'set': False,
                  'step': False,
                  'type': 'int'},
 'stream_time_pos': {'command': 'stream_time_pos',
                     'comment': 'present position in stream (in seconds)',
                     'get': True,
                     'max': False,
                     'min': 0,
                     'set': False,
                     'step': False,
                     'type': 'float'},
 'sub': {'command': 'sub',
         'comment': 'select subtitle stream',
         'get': True,
         'max': False,
         'min': -1,
         'set': True,
         'step': True,
         'type': 'int'},
 'sub_alignment': {'command': 'sub_alignment',
                   'comment': 'subtitle alignment',
                   'get': True,
                   'max': 2,
                   'min': 0,
                   'set': True,
                   'step': True,
                   'type': 'int'},
 'sub_delay': {'command': 'sub_delay',
               'comment': '',
               'get': True,
               'max': False,
               'min': False,
               'set': True,
               'step': True,
               'type': 'float'},
 'sub_demux': {'command': 'sub_demux',
               'comment': 'select subs from demux',
               'get': True,
               'max': False,
               'min': -1,
               'set': True,
               'step': True,
               'type': 'int'},
 'sub_file': {'command': 'sub_file',
              'comment': 'select file subtitles',
              'get': True,
              'max': False,
              'min': -1,
              'set': True,
              'step': True,
              'type': 'int'},
 'sub_forced_only': {'command': 'sub_forced_only',
                     'comment': '',
                     'get': True,
                     'max': 1,
                     'min': 0,
                     'set': True,
                     'step': True,
                     'type': 'flag'},
 'sub_pos': {'command': 'sub_pos',
             'comment': 'subtitle position',
             'get': True,
             'max': 100,
             'min': 0,
             'set': True,
             'step': True,
             'type': 'int'},
 'sub_scale': {'command': 'sub_scale',
               'comment': 'subtitles font size',
               'get': True,
               'max': 100,
               'min': 0,
               'set': True,
               'step': True,
               'type': 'float'},
 'sub_source': {'command': 'sub_source',
                'comment': 'select subtitle source',
                'get': True,
                'max': 2,
                'min': -1,
                'set': True,
                'step': True,
                'type': 'int'},
 'sub_visibility': {'command': 'sub_visibility',
                    'comment': 'show/hide subtitles',
                    'get': True,
                    'max': 1,
                    'min': 0,
                    'set': True,
                    'step': True,
                    'type': 'flag'},
 'sub_vob': {'command': 'sub_vob',
             'comment': 'select vobsubs',
             'get': True,
             'max': False,
             'min': -1,
             'set': True,
             'step': True,
             'type': 'int'},
 'switch_angle': {'command': 'switch_angle',
                  'comment': 'select DVD angle',
                  'get': True,
                  'max': 255,
                  'min': -2,
                  'set': True,
                  'step': True,
                  'type': 'int'},
 'switch_audio': {'command': 'switch_audio',
                  'comment': 'select audio stream',
                  'get': True,
                  'max': 255,
                  'min': -2,
                  'set': True,
                  'step': True,
                  'type': 'int'},
 'switch_program': {'command': 'switch_program',
                    'comment': '(see TAB default keybind)',
                    'get': True,
                    'max': 65535,
                    'min': -1,
                    'set': True,
                    'step': True,
                    'type': 'int'},
 'switch_title': {'command': 'switch_title',
                  'comment': 'select DVD title',
                  'get': True,
                  'max': 255,
                  'min': -2,
                  'set': True,
                  'step': True,
                  'type': 'int'},
 'switch_video': {'command': 'switch_video',
                  'comment': 'select video stream',
                  'get': True,
                  'max': 255,
                  'min': -2,
                  'set': True,
                  'step': True,
                  'type': 'int'},
 'teletext_format': {'command': 'teletext_format',
                     'comment': '0 - opaque,\n1 - transparent,\n2 - opaque inverted,\n3 - transp. inv.',
                     'get': True,
                     'max': 3,
                     'min': 0,
                     'set': True,
                     'step': True,
                     'type': 'int'},
 'teletext_half_page': {'command': 'teletext_half_page',
                        'comment': '0 - off, 1 - top half,\n2- bottom half',
                        'get': True,
                        'max': 2,
                        'min': 0,
                        'set': True,
                        'step': True,
                        'type': 'int'},
 'teletext_mode': {'command': 'teletext_mode',
                   'comment': '0 - off, 1 - on',
                   'get': True,
                   'max': 1,
                   'min': 0,
                   'set': True,
                   'step': True,
                   'type': 'flag'},
 'teletext_page': {'command': 'teletext_page',
                   'comment': '',
                   'get': True,
                   'max': 799,
                   'min': 0,
                   'set': True,
                   'step': True,
                   'type': 'int'},
 'teletext_subpage': {'command': 'teletext_subpage',
                      'comment': '',
                      'get': True,
                      'max': 64,
                      'min': 0,
                      'set': True,
                      'step': True,
                      'type': 'int'},
 'time_pos': {'command': 'time_pos',
              'comment': 'position in seconds',
              'get': True,
              'max': False,
              'min': 0,
              'set': True,
              'step': True,
              'type': 'float'},
 'tv_brightness': {'command': 'tv_brightness',
                   'comment': '',
                   'get': True,
                   'max': 100,
                   'min': -100,
                   'set': True,
                   'step': True,
                   'type': 'int'},
 'tv_contrast': {'command': 'tv_contrast',
                 'comment': '',
                 'get': True,
                 'max': 100,
                 'min': -100,
                 'set': True,
                 'step': True,
                 'type': 'int'},
 'tv_hue': {'command': 'tv_hue',
            'comment': '',
            'get': True,
            'max': 100,
            'min': -100,
            'set': True,
            'step': True,
            'type': 'int'},
 'tv_saturation': {'command': 'tv_saturation',
                   'comment': '',
                   'get': True,
                   'max': 100,
                   'min': -100,
                   'set': True,
                   'step': True,
                   'type': 'int'},
 'video_bitrate': {'command': 'video_bitrate',
                   'comment': '',
                   'get': True,
                   'max': False,
                   'min': False,
                   'set': False,
                   'step': False,
                   'type': 'int'},
 'video_codec': {'command': 'video_codec',
                 'comment': '',
                 'get': True,
                 'max': False,
                 'min': False,
                 'set': False,
                 'step': False,
                 'type': 'str'},
 'video_format': {'command': 'video_format',
                  'comment': '',
                  'get': True,
                  'max': False,
                  'min': False,
                  'set': False,
                  'step': False,
                  'type': 'int'},
 'volume': {'command': 'volume',
            'comment': 'change volume',
            'get': True,
            'max': 100,
            'min': 0,
            'set': True,
            'step': True,
            'type': 'float'},
 'vsync': {'command': 'vsync',
           'comment': '',
           'get': True,
           'max': 1,
           'min': 0,
           'set': True,
           'step': True,
           'type': 'flag'},
 'width': {'command': 'width',
           'comment': '"display" width',
           'get': True,
           'max': False,
           'min': False,
           'set': False,
           'step': False,
           'type': 'int'}}